function S_hat = decode_QAM(Y,M)
%DECODE_QAM Summary of this function goes here
%   Detailed explanation goes here
    if (M == 4)
        S_hat = 1*(real(Y) < 0 & imag(Y) >= 0) + ...
                2*(real(Y) >=0 & imag(Y) >= 0) + ...
                3*(real(Y) < 0 & imag(Y) <  0) + ...
                4*(real(Y) >=0 & imag(Y) <  0);

    elseif (M == 16)
        S_hat = 1*(                         real(Y) < -2/sqrt(10) & imag(Y) >=  2/sqrt(10)                        ) + ...
                2*(real(Y) >= -2/sqrt(10) & real(Y) <           0 & imag(Y) >=  2/sqrt(10)                        ) + ...
                3*(real(Y) >=           0 & real(Y) <  2/sqrt(10) & imag(Y) >=  2/sqrt(10)                        ) + ...
                4*(real(Y) >=  2/sqrt(10)                         & imag(Y) >=  2/sqrt(10)                        ) + ...
                5*(                         real(Y) < -2/sqrt(10) & imag(Y) >=           0 & imag(Y) <  2/sqrt(10)) + ...
                6*(real(Y) >= -2/sqrt(10) & real(Y) <           0 & imag(Y) >=           0 & imag(Y) <  2/sqrt(10)) + ...
                7*(real(Y) >=           0 & real(Y) <  2/sqrt(10) & imag(Y) >=           0 & imag(Y) <  2/sqrt(10)) + ...
                8*(real(Y) >=  2/sqrt(10)                         & imag(Y) >=           0 & imag(Y) <  2/sqrt(10)) + ...
                9*(                         real(Y) < -2/sqrt(10) & imag(Y) >= -2/sqrt(10) & imag(Y) <           0) + ...
               10*(real(Y) >= -2/sqrt(10) & real(Y) <           0 & imag(Y) >= -2/sqrt(10) & imag(Y) <           0) + ...
               11*(real(Y) >=           0 & real(Y) <  2/sqrt(10) & imag(Y) >= -2/sqrt(10) & imag(Y) <           0) + ...
               12*(real(Y) >=  2/sqrt(10)                         & imag(Y) >= -2/sqrt(10) & imag(Y) <           0) + ...
               13*(                         real(Y) < -2/sqrt(10)                          & imag(Y) < -2/sqrt(10)) + ...
               14*(real(Y) >= -2/sqrt(10) & real(Y) <           0                          & imag(Y) < -2/sqrt(10)) + ...
               15*(real(Y) >=           0 & real(Y) <  2/sqrt(10)                          & imag(Y) < -2/sqrt(10)) + ...
               16*(real(Y) >=  2/sqrt(10)                                                  & imag(Y) < -2/sqrt(10));
    else
        error('Invalid modulation order')
    end

end

